### ISSUE TITLE
When running the e2e test on saucelabs the datepicker test fails when running before 7:30 in the morning

### ISSUE THREAD

**Issue by sidohaakma** [molgenis/molgenis-ui-form#180]
## How to reproduce
Merge a pull request before 7:30 in the morning

## Expected behavior
Test succeeds

## Observed behavior
Test fails

``` Fill out date field using picker (14.412s)
 ci_safari      Expected element <#date> to have value that equals: "2018-08-02"  - expected "equals '2018-08-02'" but got: "2018-08-01"
```

**Comment by fdlk** [comment]
@ConnorStroomberg Did we fix this in #214?

**Comment by fdlk** [comment]
Fixed in #214

**Comment by fdlk** [comment]
Nope, not fixed!
```
 TEST FAILURE:  1 assertions failed, 121 passed. (4m 20s)

 ✖ field-render-tests

   - Fill out date field using picker (11.662s)
   Expected element <#date> to have value that equals: "2019-03-29"  - expected "equals '2019-03-29'" but got: "2019-03-30"
       at Object.FillOutDateFieldUsingPicker [as Fill out date field using picker] (/Users/fkelpin/git/molgenis-ui-form/test/e2e/specs/field-render-tests.js:127:20)
       at process._tickCallback (internal/process/next_tick.js:61:11)
```

**Comment by fdlk** [comment]
Bit more context: was running this locally, not on saucelabs
